[api]
dashboard = true
insecure = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.traefik]
    address = ":8080"
  [entryPoints.mysql]
    address = ":3306"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"

[docker]
domain = "local"
watch = true


[file]
watch = true


[log]
  filePath = "./log-file.log"
  format = "json"
  level = "DEBUG"

[accessLog]
  filePath = "./access.log"
  bufferingSize = 100
